#!/bin/bash

VERSION="${1}"
if [ "${VERSION}" != "7" ] && [ "${VERSION}" != "8" ] ; then
    echo "${COLOR_RED}#${COLOR_RESET}"
    echo "${COLOR_RED}#${COLOR_RESET} [${COLOR_RED}error${COLOR_RESET}] Missing choice: ${COLOR_YELLOW}7${COLOR_RESET} or ${COLOR_YELLOW}8${COLOR_RESET}"
    echo "${COLOR_RED}#${COLOR_RESET}"
    echo "${COLOR_RED}#${COLOR_RESET} For example: \"./switch 8\""
    exit 1
fi

if [ "${VERSION}" = "7" ]; then
  git checkout release/1.9.x && composer update || exit 1
fi

if [ "${VERSION}" = "8" ]; then
  git checkout release/2.x && composer update || exit 1
fi

exit 0